# -*- coding: utf-8 -*-
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# GitHub: https://github.com/btschwertfeger
#
# Based on https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    # labels:
    #   - ignore-for-release
    # authors:
    #   - john-doe
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking
        - Breaking
    - title: Implemented Enhancements 🎉
      labels:
        - Feature
        - enhancement
    - title: Fixed Bugs 🪲
      labels:
        - Bug
        - bug
    - title: Other Changes
      labels:
        - "*"
      # exclude:
      #   labels:
      #     - dependencies
    - title: 👒 Dependencies
      labels:
        - dependencies
